# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          channel: '#notification'
          message: Deployed in the dev env Successfully
        if: always()
.
